import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { JSDOM, VirtualConsole } from 'jsdom';

test('real DOM integration: workbench navigation, multi-file drafts, selection, forms, queue and native handoff', async t => {
  const errors = [], virtualConsole = new VirtualConsole(); virtualConsole.on('jsdomError', error => errors.push(error));
  const dom = new JSDOM(await readFile(new URL('../public/index.html', import.meta.url), 'utf8'), { url: 'http://127.0.0.1:4318', pretendToBeVisual: true, virtualConsole });
  const { window } = dom, document = window.document;
  window.matchMedia = () => ({ matches: false }); window.HTMLElement.prototype.scrollIntoView = () => {};
  window.HTMLCanvasElement.prototype.getContext = () => ({ fillRect() {} });
  window.HTMLDialogElement.prototype.showModal = function () { this.open = true; };
  window.HTMLDialogElement.prototype.close = function () { this.open = false; this.dispatchEvent(new window.Event('close')); };
  const original = Object.fromEntries(['window', 'document', 'Option', 'localStorage', 'requestAnimationFrame', 'EventSource', 'fetch', 'confirm', 'setTimeout'].map(key => [key, globalThis[key]]));
  const timers = new Set();
  Object.assign(globalThis, { window, document, Option: window.Option, localStorage: window.localStorage, requestAnimationFrame: fn => { fn(); return 0; }, confirm: () => true, setTimeout: (...args) => { const id = original.setTimeout(...args); timers.add(id); return id; } });
  t.after(() => { for (const timer of timers) clearTimeout(timer); Object.assign(globalThis, original); dom.window.close(); });
  const $ = id => document.getElementById(id), requests = [];
  const settle = async condition => { for (let i = 0; i < 200; i++) { if (condition()) return; await new Promise(resolve => original.setTimeout(resolve, 1)); } assert.fail(`UI did not settle; notice=${$('noticeText').textContent}; workbench=${$('workbenchStatus')?.textContent}`); };
  const submit = id => $(id).dispatchEvent(new window.Event('submit', { bubbles: true, cancelable: true }));
  const input = (id, value) => { $(id).value = value; $(id).dispatchEvent(new window.Event('input', { bubbles: true })); };
  let events;
  globalThis.EventSource = class { constructor() { this.listeners = {}; events = this; } addEventListener(name, fn) { this.listeners[name] = fn; } close() {} emit(name, value) { return this.listeners[name]?.({ data: JSON.stringify(value) }); } };
  const thread = { id: 't1', cwd: '/project', title: 'Example', revision: 1, items: [], requests: [], busy: false, mode: 'read-only', model: '', plan: false };
  const files = { 'a.py': 'x=1\n', 'b.sql': 'select a from example_table;\n' };
  globalThis.fetch = async (route, options = {}) => {
    const body = options.body ? JSON.parse(options.body) : undefined; requests.push({ route, body }); const url = new URL(route, 'http://127.0.0.1:4318'); let data;
    switch (url.pathname) {
      case '/api/bootstrap': data = { connected: true, csrf: 'test', cwd: '/project', auth: { loggedIn: true }, models: [], permissions: { options: [{ id: 'workspace-write', enabled: true }, { id: 'read-only', enabled: true }] } }; break;
      case '/api/threads': data = { cwd: '/project', threads: [thread], nextCursor: null }; break;
      case '/api/threads/t1': data = thread; break;
      case '/api/project/files': data = { cwd: '/project', entries: Object.keys(files).map(path => ({ path, name: path, kind: 'file' })), nextOffset: null }; break;
      case '/api/project/file': { const path = url.searchParams.get('path'); data = { cwd: '/project', path, content: files[path], version: 'a'.repeat(64), writable: true, newline: 'LF' }; break; }
      case '/api/project/save': files[body.path] = body.content; data = { ...body, writable: true, newline: 'LF' }; break;
      case '/api/project/search': {
        if (url.searchParams.get('query') === 'paged') {
          const cursor = url.searchParams.get('cursor');
          data = { cwd: '/project', results: cursor ? Array.from({ length: cursor === 'more' ? 5 : 200 }, (_, i) => ({ path: `paged-${(cursor === 'more' ? 200 : 0) + i}.txt`, line: 1, text: 'match' })) : [], scanned: 6000, complete: cursor === 'more', nextCursor: cursor === 'more' ? null : cursor ? 'more' : 'after-empty' };
        } else data = { cwd: '/project', results: [{ path: 'a.py', line: 1, text: files['a.py'] }], scanned: 2, limited: false };
        break;
      }
      case '/api/project/language': data = body.action === 'format' ? { content: 'x = 2\n', engine: 'Test formatter' } : { diagnostics: [], engine: 'Test static check' }; break;
      case '/api/project/replace-preview': data = { id: 'preview1', files: [{ path: 'a.py', count: 1, before: 'x=1', after: 'x=2' }] }; break;
      case '/api/project/replace-apply': data = { saved: ['a.py'] }; break;
      case '/api/send': case '/api/followup': data = { threadId: 't1' }; break;
      case '/api/capabilities': data = { skills: [], plugins: [], planSupported: true }; break;
      case '/api/connections': data = { servers: [{ name: 'demo', authStatus: 'notLoggedIn', tools: ['test'] }] }; break;
      case '/api/schedules': data = { jobs: [] }; break;
      case '/api/usage': data = { rateLimits: { primary: { usedPercent: 12 } } }; break;
      case '/api/terminal': data = { processes: [] }; break;
      case '/api/respond': case '/api/queue': data = { ok: true }; break;
      case '/api/threads/action': thread.title = body.name || thread.title; data = { threadId: 't1' }; break;
      default: throw new Error(`Unmocked ${route}`);
    }
    return { ok: true, json: async () => structuredClone(data) };
  };
  await import(`../public/app.js?dom=${Date.now()}`); await events.emit('open'); await settle(() => document.querySelectorAll('.file-main').length === 2);
  assert.equal(document.querySelectorAll('#workbenchNav [role=tab]').length, 11);
  $('workbenchButton').click(); assert.equal($('workbenchDialog').hidden, false); assert.equal($('workbenchDialog').tagName, 'SECTION');
  $('searchFilenames').checked = true; input('projectSearchQuery', 'paged'); submit('projectSearchForm');
  const resultButtons = () => [...$('projectSearchResults').querySelectorAll('button')];
  await settle(() => resultButtons().some(button => button.textContent === '下一页'));
  assert.equal(document.querySelectorAll('.search-result').length, 200, 'filename search automatically passes an empty batch');
  resultButtons().find(button => button.textContent === '下一页').click();
  await settle(() => document.querySelectorAll('.search-result').length === 5);
  assert.match($('projectSearchResults').textContent, /paged-204/);
  assert.equal(resultButtons().find(button => button.textContent === '下一页').disabled, true);
  resultButtons().find(button => button.textContent === '上一页').click();
  assert.equal(document.querySelectorAll('.search-result').length, 200);
  $('searchFilenames').checked = false;
  input('projectSearchQuery', 'x'); submit('projectSearchForm'); await settle(() => document.querySelector('.search-result'));
  document.querySelector('.search-result').click(); await settle(() => !$('fileEditor').hidden && !$('fileEditorText').readOnly); assert.equal($('workbenchDialog').hidden, false, 'search results remain beside the editor');
  input('fileEditorText', 'x=2\n');
  const bufferBeforeTheme = $('fileEditorText'), requestsBeforeTheme = requests.length;
  assert.equal($('fileEditor').dataset.layout, 'docked'); assert.equal($('editorDivider').hidden, false); assert.equal($('editorMaximize').hidden, true);
  $('editorLayoutToggle').click(); assert.equal($('fileEditor').dataset.layout, 'floating'); assert.equal($('editorDivider').hidden, true); assert.equal($('fileEditorText'), bufferBeforeTheme); assert.equal($('fileEditorText').value, 'x=2\n');
  $('editorLayoutToggle').click(); assert.equal($('fileEditor').dataset.layout, 'docked'); assert.equal($('editorDivider').hidden, false); assert.equal($('fileEditorText'), bufferBeforeTheme);
  input('prompt', 'keep my draft'); bufferBeforeTheme.setSelectionRange(1, 3);
  $('themeToggle').click(); assert.equal(document.documentElement.dataset.theme, 'light'); assert.equal($('fileEditorText'), bufferBeforeTheme); assert.equal($('fileEditorText').value, 'x=2\n'); assert.equal($('fileEditorText').selectionStart, 1); assert.equal($('prompt').value, 'keep my draft');
  $('themeToggle').click(); assert.equal(document.documentElement.dataset.theme, 'dark'); assert.equal(requests.length, requestsBeforeTheme, 'theme switching never calls the server');
  document.querySelector('.file-main[aria-label="打开编辑：b.sql"]').click(); await settle(() => $('editorFilename').textContent === 'b.sql' && !$('fileEditorText').readOnly);
  input('fileEditorText', 'select b from example_table;\n'); assert.equal(document.querySelectorAll('.editor-tab').length, 2);
  document.querySelector('[role=tab][aria-label="a.py，未保存"]').click(); assert.equal($('fileEditorText').value, 'x=2\n');
  $('editorFormatCode').click(); await settle(() => $('fileEditorText').value === 'x = 2\n'); assert.equal(files['a.py'], 'x=1\n', 'formatting does not save disk');
  $('fileEditorText').setSelectionRange(0, 5); $('editorSelection').click(); assert.match($('prompt').value, /a\.py:1-1/); assert.match($('prompt').value, /x = 2/); assert.equal($('fileEditor').hidden, false);
  document.querySelector('.file-main[aria-label="打开编辑：a.py"]').click(); $('editorSaveAll').click(); await settle(() => files['a.py'] === 'x = 2\n' && files['b.sql'].includes('select b'));
  assert.equal($('editorSaveAll').disabled, true);
  $('editorMinimize').click(); input('prompt', 'new request'); submit('composer'); await settle(() => requests.some(r => r.route === '/api/send'));
  await settle(() => !$('composer').getAttribute('aria-busy') || $('composer').getAttribute('aria-busy') === 'false');
  await events.emit('thread', { ...thread, revision: 3, busy: true, turnId: 'turn1', requests: [], tokenUsage: { total: { totalTokens: 123 }, last: { inputTokens: 50 }, modelContextWindow: 1000 } });
  assert.equal($('sendButton').hidden, false); assert.equal($('followupBehavior').hidden, false); assert.match($('tokenUsage').textContent, /123/);
  assert.equal($('currentThreadStatus').textContent, '运行中'); assert.match($('activeThreadList').textContent, /Example/); assert.match($('activeThreadList').textContent, /运行中/); assert.match(document.title, /Example/);
  assert.equal(document.querySelector('.thread-button[data-thread-id="t1"] .thread-status').textContent, '运行中', 'live state overrides the stale history summary');
  await events.emit('thread', { ...thread, id: 'background', cwd: '/another-project', title: '另一个项目的长名称任务', revision: 1, busy: true });
  assert.equal($('activityCount').textContent, '2'); assert.match($('activeThreadList').textContent, /another-project/);
  input('prompt', 'follow up'); $('followupBehavior').value = 'queue'; submit('composer'); await settle(() => requests.some(r => r.route === '/api/followup'));
  assert.equal(requests.find(r => r.route === '/api/followup').body.behavior, 'queue');
  await settle(() => $('composer').getAttribute('aria-busy') === 'false');
  await events.emit('thread', { ...thread, revision: 4, busy: true, turnId: 'turn1', queue: [{ id: 'q1', text: 'pending message' }], queuePaused: false, requests: [{ key: 'mcp1', method: 'mcpServer/elicitation/request', params: { mode: 'form', serverName: 'demo', message: 'Test schema', requestedSchema: { type: 'object', required: ['count'], properties: { count: { type: 'integer', minimum: 1 }, choice: { type: 'string', enum: ['a', 'b'] } } } } }] });
  assert.match($('messageQueue').textContent, /pending message/);
  assert.equal($('currentThreadStatus').textContent, '待确认'); assert.match($('activeThreadList').textContent, /待确认/);
  const mcp = document.querySelector('#requests form'); mcp.querySelector('[name=count]').value = '2'; mcp.querySelector('[name=choice]').value = 'b'; mcp.dispatchEvent(new window.Event('submit', { cancelable: true }));
  await settle(() => requests.some(r => r.route === '/api/respond')); assert.deepEqual(requests.find(r => r.route === '/api/respond').body.content, { count: 2, choice: 'b' });
  await events.emit('thread', { ...thread, revision: 5, busy: false, completion: 'completed' }); assert.equal($('currentThreadStatus').textContent, '已完成'); assert.equal($('activityCount').textContent, '1');
  await events.emit('error'); assert.match($('activeThreadList').textContent, /待核实/); assert.equal($('activityHeading').textContent, '任务状态待同步');
  const oldStream = events;
  window.dispatchEvent(new window.Event('online'));
  await settle(() => events !== oldStream);
  await events.emit('open');
  await events.emit('snapshot', { connected: true, threads: [{ ...thread, revision: 1, busy: false, completion: 'completed' }] });
  assert.equal(document.querySelector('.active-thread[data-thread-id="background"] .thread-status').textContent, '待核实', 'a service restart must not resurrect stale running statuses');
  await events.emit('thread', { ...thread, id: 'background', cwd: '/another-project', title: '重新同步的任务', revision: 1, busy: true });
  assert.equal(document.querySelector('.active-thread[data-thread-id="background"] .thread-status').textContent, '运行中');
  $('conversationTitleButton').click(); assert.equal($('threadActionsDialog').open, true); assert.equal($('threadRename').value, 'Example'); $('closeThreadActions').click();
  $('settingsButton').click(); document.querySelector('[data-tab=native]').click(); assert.equal(document.querySelector('[data-panel=native]').hidden, false); assert.match($('nativeCapabilities').textContent, /网页暂不支持/); assert.ok(document.querySelector('[data-panel=native] a[href="codex://"]'));
  document.querySelector('[data-tab=preferences]').click(); $('persistDrafts').checked = true; $('persistDrafts').dispatchEvent(new window.Event('change')); assert.equal(localStorage.getItem('codex-desk:persistDrafts'), 'true');
  document.querySelector('[data-tab=connections]').click(); await settle(() => $('connectionsResults').textContent.includes('demo'));
  document.querySelector('[data-tab=search]').click(); assert.equal(document.querySelector('[data-panel=search]').hidden, false);
  const ids = [...document.querySelectorAll('[id]')].map(el => el.id); assert.equal(new Set(ids).size, ids.length, 'no duplicate IDs across dynamic editor and workbench');
  assert.deepEqual(errors.map(error => error.message), []);
});
